In [40]:
import pandas as pd
from scipy.interpolate import interp1d
import numpy as np

In [15]:
df_usgs_mcs = pd.read_excel(r'data/data_minerals/USGS/data_usgs.xlsx', sheet_name='data_min_commodities')
df_usgs_my = pd.read_excel(r'data/data_minerals/USGS/data_usgs.xlsx', sheet_name='data_min_yearbook')

In [16]:
df_usgs_mcs

,SOURCE,COMMODITY,COUNTRY,YEAR,TYPE,UNIT,VALUE
0,MCS2022,Aluminum,World,2020,"Smelter production, aluminum",kt,65100
1,MCS2023,Aluminum,World,2021,"Smelter production, aluminum",kt,67500
2,MCS2024,Aluminum,World,2022,"Smelter production, aluminum",kt,68400
3,MCS2025,Aluminum,World,2023,"Smelter production, aluminum",kt,70000
4,MCS2025,Aluminum,World,2024,"Smelter production, aluminum",kt,72000
5,MCS2022,Copper,World,2020,"Mine production, recoverable copper content",kt,20600
6,MCS2023,Copper,World,2021,"Mine production, recoverable copper content",kt,21200
7,MCS2024,Copper,World,2022,"Mine production, recoverable copper content",kt,21900
8,MCS2025,Copper,World,2023,"Mine production, recoverable copper content",kt,22600
9,MCS2025,Copper,World,2024,"Mine production, recoverable copper content",kt,23000
10,MCS2022,Copper,World,2020,"Refinery production, copper",kt,25300
11,MCS2023,Copper,World,2021,"Refinery production, copper",kt,25300
12,MCS2024,Copper,World,2022,"Refinery production, copper",kt,25900
13,MCS2025,Copper,World,2023,"Refinery production, copper",kt,27000
14,MCS2025,Copper,World,2024,"Refinery production, copper",kt,27000
15,MCS2022,Graphite,World,2020,Mine production,t,966000
16,MCS2023,Graphite,World,2021,Mine production,t,1130000
17,MCS2024,Graphite,World,2022,Mine production,t,1680000
18,MCS2025,Graphite,World,2023,Mine production,t,1530000
19,MCS2025,Graphite,World,2024,Mine production,t,1600000
20,MCS2022,Nickel,World,2020,"Mine production, nickel content",t,2510000
21,MCS2023,Nickel,World,2021,"Mine production, nickel content",t,2730000
22,MCS2024,Nickel,World,2022,"Mine production, nickel content",t,3270000
23,MCS2025,Nickel,World,2023,"Mine production, nickel content",t,3750000
24,MCS2025,Nickel,World,2024,"Mine production, nickel content",t,3700000
25,MCS2022,Silicon,World,2020,"Plant production, Ferosilicon, silicon content",kt,NaN
26,MCS2023,Silicon,World,2021,"Plant production, Ferosilicon, silicon content",kt,-
27,MCS2024,Silicon,World,2022,"Plant production, Ferosilicon, silicon content",kt,5440
28,MCS2025,Silicon,World,2023,"Plant production, Ferosilicon, silicon content",kt,5190
29,MCS2025,Silicon,World,2024,"Plant production, Ferosilicon, silicon content",kt,5100
30,MCS2022,Silicon,World,2020,"Plant production, silicon metal",kt,NaN
31,MCS2023,Silicon,World,2021,"Plant production, silicon metal",kt,-
32,MCS2024,Silicon,World,2022,"Plant production, silicon metal",kt,3670
33,MCS2025,Silicon,World,2023,"Plant production, silicon metal",kt,4280
34,MCS2025,Silicon,World,2024,"Plant production, silicon metal",kt,4600
35,MCS2022,Silicon,World,2020,"Plant production, silicon content of combined ...",kt,8120
36,MCS2023,Silicon,World,2021,"Plant production, silicon content of combined ...",kt,9150
37,MCS2024,Silicon,World,2022,"Plant production, silicon content of combined ...",kt,NaN
38,MCS2025,Silicon,World,2023,"Plant production, silicon content of combined ...",kt,NaN
39,MCS2025,Silicon,World,2024,"Plant production, silicon content of combined ...",kt,NaN

In [20]:
df_usgs_my

,SOURCE,COMMODITY,COUNTRY,YEAR,TYPE,SUBTYPE,UNIT,VALUE,COMMENT
0,Mineral yearbook,Aluminum,World,2021,Smelter production,Primary,kt,67500,Primary aluminum is defined as “The weight of ...
1,Mineral yearbook,Copper,World,2020,Mine production,Total,t,20600000,"tons, copper content"
2,Mineral yearbook,Copper,World,2020,Mine production,Total|Concentrates,t,16400000,"tons, copper content"
3,Mineral yearbook,Copper,World,2020,Mine production,"Total|Leaching, electrowon",t,4190000,"tons, copper content"
4,Mineral yearbook,Copper,World,2020,Smelter production,Total,t,21200000,"tons, copper content"
5,Mineral yearbook,Copper,World,2020,Smelter production,Total|Primary,t,17800000,"tons, copper content"
6,Mineral yearbook,Copper,World,2020,Smelter production,Total|Secondary,t,3390000,"tons, copper content"
7,Mineral yearbook,Copper,World,2020,Refinery production,Total,t,25000000,NaN
8,Mineral yearbook,Copper,World,2020,Refinery production,Total|Primary,t,21100000,NaN
9,Mineral yearbook,Copper,World,2020,Refinery production,"Total|Primary|Leaching, electrowon",t,4190000,NaN
10,Mineral yearbook,Copper,World,2020,Refinery production,Total|Primary|Other,t,16900000,NaN
11,Mineral yearbook,Copper,World,2020,Refinery production,Total|Secondary,t,3970000,NaN
12,Mineral yearbook,Nickel,World,2021,Refinery production,Total,t,2560000,"tons, nickel content. Primary nickel refers to..."
13,Mineral yearbook,Nickel,World,2021,Refinery production,Total|Chemicals,t,117000,"tons, nickel content. Primary nickel refers to..."
14,Mineral yearbook,Nickel,World,2021,Refinery production,Total|Ferronickel,t,1570000,"tons, nickel content. Primary nickel refers to..."
15,Mineral yearbook,Nickel,World,2021,Refinery production,Total|Metal,t,695000,"tons, nickel content. Primary nickel refers to..."
16,Mineral yearbook,Nickel,World,2021,Refinery production,Total|Oxide sinter,t,65900,"tons, nickel content. Primary nickel refers to..."
17,Mineral yearbook,Nickel,World,2021,Refinery production,Total|Unspecified,t,109000,"tons, nickel content. Primary nickel refers to..."
18,Mineral yearbook,Graphite,World,2022,Mine production,Total,t,1680000,NaN
19,Mineral yearbook,Graphite,World,2022,Mine production,Total|Amorphous,t,208000,NaN
20,Mineral yearbook,Graphite,World,2022,Mine production,Total|Crystalline flake,t,1470000,NaN
21,Mineral yearbook,Graphite,World,2022,Mine production,Total|Vein or lump,t,3300,NaN
22,Mineral yearbook,Silicon,World,2022,Refinery production,Total,t,12500000,"tons, gross weight"
23,Mineral yearbook,Silicon,World,2022,Refinery production,Total|Ferrosilicon,t,8360000,"tons, gross weight"
24,Mineral yearbook,Silicon,World,2022,Refinery production,Total|Silicon metal,t,3750000,"tons, gross weight"

# Calculation of mineral demand for the all economy

## Mineral yearbook update based on Mineral commodities

In [34]:
def update_mineral_yearbook(df_yearbook, df_mcs, target_year=2024):
    """
    Updates the Mineral Yearbook dataset by adding missing years up to `target_year`
    using the corresponding annual growth rate from the MCS dataset. Growth rates 
    are applied to all subtypes of a given COMMODITY and TYPE.

    Parameters:
        df_yearbook (pd.DataFrame): Mineral Yearbook dataset.
        df_mcs (pd.DataFrame): MCS dataset with mapped TYPE values.
        target_year (int): The year up to which data should be updated.

    Returns:
        pd.DataFrame: Updated Mineral Yearbook dataset with new extrapolated values.
    """

    # Standardize commodity names and country names to match
    df_mcs["COMMODITY"] = df_mcs["COMMODITY"].str.strip()
    df_mcs["COUNTRY"] = df_mcs["COUNTRY"].replace({"World total (rounded)": "World"})

    # Define the TYPE mapping dictionary
    type_mapping = {
        "Smelter production, aluminum": "Smelter production",
        "Mine production, recoverable copper content": "Mine production",
        "Refinery production, copper": "Refinery production",
        "Mine production, nickel content": "Mine production",
        "Plant production, Ferosilicon, silicon content ": "Refinery production",
        "Plant production, silicon metal": "Refinery production",
        "Plant production, silicon content of combined totals for ferrosilicon and silicon metal production": "Refinery production",
        
        # Additional mappings based on missing values
        "Mine production": "Mine production",
        "Smelter production": "Smelter production",
        "Refinery production": "Refinery production"
    }

    # Apply TYPE mapping
    df_mcs["TYPE_MAPPED"] = df_mcs["TYPE"].map(type_mapping).fillna(df_mcs["TYPE"])

    # Convert VALUE column to numeric
    df_mcs["VALUE"] = pd.to_numeric(df_mcs["VALUE"], errors="coerce")
    df_yearbook["VALUE"] = pd.to_numeric(df_yearbook["VALUE"], errors="coerce")

    updated_rows = []

    # Get the latest year for each COMMODITY, COUNTRY, TYPE (ignoring SUBTYPE for now)
    latest_yearbook = df_yearbook.groupby(["COMMODITY", "COUNTRY", "TYPE"])["YEAR"].max().reset_index()

    for _, row in latest_yearbook.iterrows():
        commodity, country, data_type, last_year = row["COMMODITY"], row["COUNTRY"], row["TYPE"], row["YEAR"]

        # Filter MCS data for the relevant COMMODITY, COUNTRY, TYPE
        mcs_filtered = df_mcs[
            (df_mcs["COMMODITY"] == commodity) & 
            (df_mcs["COUNTRY"] == country) & 
            (df_mcs["TYPE_MAPPED"] == data_type)
        ].sort_values("YEAR")

        if len(mcs_filtered) < 2:
            # If we don't have enough data points, skip this commodity
            continue

        # Compute the annual growth rates from MCS data
        mcs_filtered["growth_rate"] = mcs_filtered["VALUE"].pct_change()

        # Find all subtypes for this COMMODITY, COUNTRY, TYPE in the Yearbook
        subtypes = df_yearbook[
            (df_yearbook["COMMODITY"] == commodity) & 
            (df_yearbook["COUNTRY"] == country) & 
            (df_yearbook["TYPE"] == data_type)
        ][["SUBTYPE", "VALUE", "UNIT"]].drop_duplicates()

        for _, sub_row in subtypes.iterrows():
            subtype, last_value, unit = sub_row["SUBTYPE"], sub_row["VALUE"], sub_row["UNIT"]

            if pd.isna(last_value):
                continue

            new_year = last_year

            # Predict values year by year using corresponding annual growth rate
            while new_year < target_year:
                next_year = new_year + 1

                # Find the corresponding growth rate for this year
                if next_year in mcs_filtered["YEAR"].values:
                    growth_rate = mcs_filtered.loc[mcs_filtered["YEAR"] == next_year, "growth_rate"].values[0]
                else:
                    growth_rate = 0  # If no growth rate is available, assume no growth

                if pd.isna(growth_rate):
                    growth_rate = 0

                # Apply the annual growth rate
                last_value *= (1 + growth_rate)

                # Create a new row for the updated yearbook dataset
                new_row = {
                    "SOURCE": "Mineral yearbook (Updated)",
                    "COMMODITY": commodity,
                    "COUNTRY": country,
                    "YEAR": next_year,
                    "TYPE": data_type,
                    "SUBTYPE": subtype,
                    "UNIT": unit,
                    "VALUE": round(last_value, 2),
                    "COMMENT": f"Extrapolated from {new_year} using MCS growth rate for {next_year} ({growth_rate:.2%})."
                }
                updated_rows.append(new_row)

                # Move to the next year
                new_year = next_year

    # Append new rows to the existing DataFrame
    df_updated = pd.concat([df_yearbook, pd.DataFrame(updated_rows)], ignore_index=True)
    df_updated = df_updated.sort_values(by=["COMMODITY", "YEAR"], ascending=[True, True])

    return df_updated

In [35]:
df_yearbook_updated = update_mineral_yearbook(df_usgs_my, df_usgs_mcs)

C:\Users\mp_ma\AppData\Local\Temp\ipykernel_12100\3304106882.py:63: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  mcs_filtered["growth_rate"] = mcs_filtered["VALUE"].pct_change()

In [36]:
df_yearbook_updated

,SOURCE,COMMODITY,COUNTRY,YEAR,TYPE,SUBTYPE,UNIT,VALUE,COMMENT
0,Mineral yearbook,Aluminum,World,2021,Smelter production,Primary,kt,67500.00,Primary aluminum is defined as “The weight of ...
25,Mineral yearbook (Updated),Aluminum,World,2022,Smelter production,Primary,kt,68400.00,Extrapolated from 2021 using MCS growth rate f...
26,Mineral yearbook (Updated),Aluminum,World,2023,Smelter production,Primary,kt,70000.00,Extrapolated from 2022 using MCS growth rate f...
27,Mineral yearbook (Updated),Aluminum,World,2024,Smelter production,Primary,kt,72000.00,Extrapolated from 2023 using MCS growth rate f...
1,Mineral yearbook,Copper,World,2020,Mine production,Total,t,20600000.00,"tons, copper content"
...,...,...,...,...,...,...,...,...,...
70,Mineral yearbook (Updated),Silicon,World,2023,Refinery production,Total|Ferrosilicon,t,11822452.32,Extrapolated from 2022 using MCS growth rate f...
72,Mineral yearbook (Updated),Silicon,World,2023,Refinery production,Total|Silicon metal,t,5303133.51,Extrapolated from 2022 using MCS growth rate f...
69,Mineral yearbook (Updated),Silicon,World,2024,Refinery production,Total,t,21063848.07,Extrapolated from 2023 using MCS growth rate f...
71,Mineral yearbook (Updated),Silicon,World,2024,Refinery production,Total|Ferrosilicon,t,14087501.59,Extrapolated from 2023 using MCS growth rate f...
73,Mineral yearbook (Updated),Silicon,World,2024,Refinery production,Total|Silicon metal,t,6319154.42,Extrapolated from 2023 using MCS growth rate f...

In [37]:
#df_yearbook_updated.to_csv(r'df_yearbook_updated.csv', index=False)

## Projection to 2050 using population or GDP

In [38]:
iamdf_ssp = pd.read_csv(r'data/data_ssp/iamdf_ssp.csv')

In [42]:
iamdf_ssp

,model,scenario,region,variable,unit,1950,1955,1960,1965,1970,...,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
0,IIASA GDP 2023,SSP2,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,255138.335123,277925.973504,303738.457766,329904.061454,355181.883172,379416.234223,403091.576433,426844.242781,451003.054434,4.736919e+05
1,IIASA GDP 2023,SSP3,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,225693.405454,237807.806366,251465.089082,263876.784353,274109.176024,282837.904227,291093.415351,299532.073994,308528.092060,3.176999e+05
2,IIASA GDP 2023,SSP4,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,242718.489915,262626.219514,286025.130813,309511.569348,331753.809478,353275.893133,375617.507533,399219.452589,424297.929059,4.497758e+05
3,IIASA GDP 2023,SSP5,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,303063.278481,339134.662984,381314.518550,422795.651999,460310.806649,492471.244082,519576.501571,542624.652729,564477.011532,5.835374e+05
4,IIASA-WiC POP 2023,Historical Reference,World,Population,million,2476.354507,2717.192825,2993.980903,3300.599684,3655.64095,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,IIASA-WiC POP 2023,SSP1,World,Population,million,NaN,NaN,NaN,NaN,NaN,...,9202.151029,9213.262946,9178.893434,9106.377915,8999.413476,8858.470328,8682.371633,8474.137111,8238.814653,7.979164e+03
6,IIASA-WiC POP 2023,SSP2,World,Population,million,NaN,NaN,NaN,NaN,NaN,...,9773.968144,9915.120022,10018.007006,10087.997781,10125.479114,10129.680830,10103.453315,10052.324966,9979.043839,9.884518e+03
7,IIASA-WiC POP 2023,SSP3,World,Population,million,NaN,NaN,NaN,NaN,NaN,...,10434.441507,10770.760005,11094.131841,11406.313579,11703.830762,11987.472742,12262.506162,12533.952723,12800.281382,1.305898e+04
8,IIASA-WiC POP 2023,SSP4,World,Population,million,NaN,NaN,NaN,NaN,NaN,...,10233.976397,10513.499547,10768.949236,11001.646474,11210.018164,11395.574578,11563.790683,11720.583524,11865.380260,1.199471e+04
9,IIASA-WiC POP 2023,SSP5,World,Population,million,NaN,NaN,NaN,NaN,NaN,...,9201.376985,9213.460664,9180.525398,9110.103583,9006.029578,8868.761464,8696.932656,8493.238260,8262.352940,8.006621e+03
10,OECD ENV-Growth 2023,Historical Reference,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,OECD ENV-Growth 2023,SSP1,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,342519.622140,379875.668420,418481.884650,456578.197690,493592.064640,529005.618020,562481.066850,593986.279530,623451.253340,6.504840e+05
12,OECD ENV-Growth 2023,SSP2,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,311753.182600,343908.603280,378120.862750,413225.062780,449104.420620,485594.601470,522887.292160,561317.292620,600977.663520,6.416547e+05
13,OECD ENV-Growth 2023,SSP3,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,258392.181650,271794.227522,284623.679793,296334.880140,307271.673330,317678.260000,327919.571200,338267.024440,348766.663470,3.593982e+05
14,OECD ENV-Growth 2023,SSP4,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,303488.802611,329395.882470,355920.720090,382261.602350,408559.430700,434932.974930,461740.283460,489472.059910,518486.839400,5.489459e+05
15,OECD ENV-Growth 2023,SSP5,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,409164.586980,469503.373190,535195.614480,604238.057190,675916.326720,749501.136010,824441.939340,900572.336930,977617.488740,1.054733e+06

In [46]:
def project_mineral_yearbook(df_yearbook, iamdf_ssp, model, scenario, variable, target_year=2050):
    """
    Projects mineral yearbook data using SSP-derived GDP or population growth rates.

    Parameters:
        df_yearbook (pd.DataFrame): Mineral Yearbook dataset.
        iamdf_ssp (pd.DataFrame): IAM SSP dataset with GDP/Population projections.
        model (str): The selected model (e.g., 'IIASA GDP 2023').
        scenario (str): The selected scenario (e.g., 'SSP2').
        variable (str): The selected variable ('GDP|PPP' or 'Population').
        target_year (int): The year up to which projections should be made.

    Returns:
        pd.DataFrame: Updated Yearbook dataset with projections.
    """
    projected_rows = []

    # Filter SSP dataset based on user selection
    ssp_filtered = iamdf_ssp[
        (iamdf_ssp["model"] == model) & 
        (iamdf_ssp["scenario"] == scenario) & 
        (iamdf_ssp["variable"] == variable) &
        (iamdf_ssp["region"] == "World")  # Ensure global values
    ]

    if ssp_filtered.empty:
        raise ValueError("No matching data found for the selected model, scenario, and variable.")

    # Extract available years and values for interpolation
    years_available = np.array([2020, 2025])
    values_available = ssp_filtered[[str(y) for y in years_available]].values.flatten()

    # Interpolate for missing years (linear interpolation)
    interp_func = interp1d(years_available, values_available, kind="linear", fill_value="extrapolate")
    interpolated_years = np.arange(2020, target_year + 1)
    interpolated_values = interp_func(interpolated_years)

    # Compute year-specific growth rates
    growth_rates = np.diff(interpolated_values) / interpolated_values[:-1]

    # Get latest available year in Yearbook data
    latest_year = df_yearbook["YEAR"].max()

    # Project mineral production using SSP growth rates
    for _, row in df_yearbook.iterrows():
        commodity, country, data_type, subtype, last_value, unit = (
            row["COMMODITY"], row["COUNTRY"], row["TYPE"], row["SUBTYPE"], row["VALUE"], row["UNIT"]
        )

        new_value = last_value
        for i, year in enumerate(range(latest_year + 1, target_year + 1)):
            growth_rate = growth_rates[min(i, len(growth_rates) - 1)]  # Ensure valid index
            new_value *= (1 + growth_rate)

            projected_rows.append({
                "SOURCE": "Mineral yearbook (Projected)",
                "COMMODITY": commodity,
                "COUNTRY": country,
                "YEAR": year,
                "TYPE": data_type,
                "SUBTYPE": subtype,
                "UNIT": unit,
                "VALUE": round(new_value, 2),
                "COMMENT": f"Projected using {variable} growth rate ({growth_rate:.2%})."
            })

    # Append projected data to original DataFrame
    df_projected = pd.concat([df_yearbook, pd.DataFrame(projected_rows)], ignore_index=True)
    df_projected = df_projected.sort_values(by=["COMMODITY", "YEAR"], ascending=[True, True])
    
    return df_projected

In [47]:
df_projected = project_mineral_yearbook(df_yearbook_updated, iamdf_ssp, model="IIASA-WiC POP 2023", scenario="SSP2", variable="Population")

In [48]:
df_projected

,SOURCE,COMMODITY,COUNTRY,YEAR,TYPE,SUBTYPE,UNIT,VALUE,COMMENT
0,Mineral yearbook,Aluminum,World,2021,Smelter production,Primary,kt,67500.00,Primary aluminum is defined as “The weight of ...
1,Mineral yearbook (Updated),Aluminum,World,2022,Smelter production,Primary,kt,68400.00,Extrapolated from 2021 using MCS growth rate f...
2,Mineral yearbook (Updated),Aluminum,World,2023,Smelter production,Primary,kt,70000.00,Extrapolated from 2022 using MCS growth rate f...
3,Mineral yearbook (Updated),Aluminum,World,2024,Smelter production,Primary,kt,72000.00,Extrapolated from 2023 using MCS growth rate f...
74,Mineral yearbook (Projected),Aluminum,World,2025,Smelter production,Primary,kt,68099.63,Projected using Population growth rate (0.89%).
...,...,...,...,...,...,...,...,...,...
1893,Mineral yearbook (Projected),Silicon,World,2050,Refinery production,Total|Ferrosilicon,t,14553050.53,Projected using Population growth rate (0.73%).
1919,Mineral yearbook (Projected),Silicon,World,2050,Refinery production,Total|Silicon metal,t,6527983.18,Projected using Population growth rate (0.73%).
1945,Mineral yearbook (Projected),Silicon,World,2050,Refinery production,Total,t,25928905.19,Projected using Population growth rate (0.73%).
1971,Mineral yearbook (Projected),Silicon,World,2050,Refinery production,Total|Ferrosilicon,t,17341251.79,Projected using Population growth rate (0.73%).
1997,Mineral yearbook (Projected),Silicon,World,2050,Refinery production,Total|Silicon metal,t,7778671.56,Projected using Population growth rate (0.73%).